



struct _ecore_sdl_keys_s
{
   int          code;
   const char*  name;
   const char*  compose;
};

static const struct _ecore_sdl_keys_s  keystable[] =
{
   { G_KEY_UNKNOWN,      "0x00",         "" },
   { G_KEY_FIRST,        "First",        "First" },
   //{ G_KEY_ENTER,        "LineFeed",        "LineFeed" },
   { G_KEY_BACKSPACE,    "BackSpace",    "BackSpace" },
   { G_KEY_TAB,          "Tab",          "Tab" },
   { G_KEY_CLEAR,        "Clear",        "Clear" },
   { G_KEY_RETURN,       "Return",       "Return" },
   { G_KEY_PAUSE,        "Pause",        "Pause" },
   { G_KEY_ESCAPE,       "Escape",       "Escape" },
   { G_KEY_SPACE,        "space",        " " },
   { G_KEY_EXCLAIM,      "exclam",       "!" },
   { G_KEY_QUOTEDBL,     "quotedbl",     "\"" },
   { G_KEY_HASH,         "numbersign",   "#" },
   { G_KEY_DOLLAR,       "dollar",       "$" },
   { G_KEY_AMPERSAND,    "ampersand",    "&" },
   { G_KEY_QUOTE,        "apostrophe",   "'" },
   { G_KEY_LEFTPAREN,    "parenleft",    "(" },
   { G_KEY_RIGHTPAREN,   "parenright",   ")" },
   { G_KEY_ASTERISK,     "asterik",      "*" },
   { G_KEY_PLUS,         "plus",         "+" },
   { G_KEY_COMMA,        "comma",        "," },
   { G_KEY_MINUS,        "minus",        "-" },
   { G_KEY_PERIOD,       "period",       "." },
   { G_KEY_SLASH,        "slash",        "/" },
   { G_KEY_0,            "0",            "0" },
   { G_KEY_1,            "1",            "1" },
   { G_KEY_2,            "2",            "2" },
   { G_KEY_3,            "3",            "3" },
   { G_KEY_4,            "4",            "4" },
   { G_KEY_5,            "5",            "5" },
   { G_KEY_6,            "6",            "6" },
   { G_KEY_7,            "7",            "7" },
   { G_KEY_8,            "8",            "8" },
   { G_KEY_9,            "9",            "9" },
   { G_KEY_COLON,        "colon",        ":" },
   { G_KEY_SEMICOLON,    "semicolon",    ";" },
   { G_KEY_LESS,         "less",         "<" },
   { G_KEY_EQUALS,       "equal",        "=" },
   { G_KEY_GREATER,      "greater",      ">" },
   { G_KEY_QUESTION,     "question",     "?" },
   { G_KEY_AT,           "at",           "@" },

   /* Skip uppercase letters */
   { G_KEY_LEFTBRACKET,  "bracketleft",  "[" },
   { G_KEY_BACKSLASH,    "backslash",    "\\" },
   { G_KEY_RIGHTBRACKET, "bracketright", "]" },
   { G_KEY_CARET,        "asciicircumm", "^" },
   { G_KEY_UNDERSCORE,   "underscore",   "_" },
   { G_KEY_BACKQUOTE,    "asciitilde",   "`" },
   { G_KEY_a,            "a",            "a" },
   { G_KEY_b,            "b",            "b" },
   { G_KEY_c,            "c",            "c" },
   { G_KEY_d,            "d",            "d" },
   { G_KEY_e,            "e",            "e" },
   { G_KEY_f,            "f",            "f" },
   { G_KEY_g,            "g",            "g" },
   { G_KEY_h,            "h",            "h" },
   { G_KEY_i,            "i",            "i" },
   { G_KEY_j,            "j",            "j" },
   { G_KEY_k,            "k",            "k" },
   { G_KEY_l,            "l",            "l" },
   { G_KEY_m,            "m",            "m" },
   { G_KEY_n,            "n",            "n" },
   { G_KEY_o,            "o",            "o" },
   { G_KEY_p,            "p",            "p" },
   { G_KEY_q,            "q",            "q" },
   { G_KEY_r,            "r",            "r" },
   { G_KEY_s,            "s",            "s" },
   { G_KEY_t,            "t",            "t" },
   { G_KEY_u,            "u",            "u" },
   { G_KEY_v,            "v",            "v" },
   { G_KEY_w,            "w",            "w" },
   { G_KEY_x,            "x",            "x" },
   { G_KEY_y,            "y",            "y" },
   { G_KEY_z,            "z",            "z" },
   { G_KEY_DELETE,       "Delete",       "\177" },
   /* End of ASCII mapped keysyms */

   /* International keyboard syms */
   { G_KEY_WORLD_0,      "w0",           "" }, /* 0xA0 */
   { G_KEY_WORLD_1,      "w1",           "" },
   { G_KEY_WORLD_2,      "w2",           "" },
   { G_KEY_WORLD_3,      "w3",           "" },
   { G_KEY_WORLD_4,      "w4",           "" },
   { G_KEY_WORLD_5,      "w5",           "" },
   { G_KEY_WORLD_6,      "w6",           "" },
   { G_KEY_WORLD_7,      "w7",           "" },
   { G_KEY_WORLD_8,      "w8",           "" },
   { G_KEY_WORLD_9,      "w9",           "" },
   { G_KEY_WORLD_10,     "w10",          "" },
   { G_KEY_WORLD_11,     "w11",          "" },
   { G_KEY_WORLD_12,     "w12",          "" },
   { G_KEY_WORLD_13,     "w13",          "" },
   { G_KEY_WORLD_14,     "w14",          "" },
   { G_KEY_WORLD_15,     "w15",          "" },
   { G_KEY_WORLD_16,     "w16",          "" },
   { G_KEY_WORLD_17,     "w17",          "" },
   { G_KEY_WORLD_18,     "w18",          "" },
   { G_KEY_WORLD_19,     "w19",          "" },
   { G_KEY_WORLD_20,     "w20",          "" },
   { G_KEY_WORLD_21,     "w21",          "" },
   { G_KEY_WORLD_22,     "w22",          "" },
   { G_KEY_WORLD_23,     "w23",          "" },
   { G_KEY_WORLD_24,     "w24",          "" },
   { G_KEY_WORLD_25,     "w25",          "" },
   { G_KEY_WORLD_26,     "w26",          "" },
   { G_KEY_WORLD_27,     "w27",          "" },
   { G_KEY_WORLD_28,     "w28",          "" },
   { G_KEY_WORLD_29,     "w29",          "" },
   { G_KEY_WORLD_30,     "w30",          "" },
   { G_KEY_WORLD_31,     "w31",          "" },
   { G_KEY_WORLD_32,     "w32",          "" },
   { G_KEY_WORLD_33,     "w33",          "" },
   { G_KEY_WORLD_34,     "w34",          "" },
   { G_KEY_WORLD_35,     "w35",          "" },
   { G_KEY_WORLD_36,     "w36",          "" },
   { G_KEY_WORLD_37,     "w37",          "" },
   { G_KEY_WORLD_38,     "w38",          "" },
   { G_KEY_WORLD_39,     "w39",          "" },
   { G_KEY_WORLD_40,     "w40",          "" },
   { G_KEY_WORLD_41,     "w41",          "" },
   { G_KEY_WORLD_42,     "w42",          "" },
   { G_KEY_WORLD_43,     "w43",          "" },
   { G_KEY_WORLD_44,     "w44",          "" },
   { G_KEY_WORLD_45,     "w45",          "" },
   { G_KEY_WORLD_46,     "w46",          "" },
   { G_KEY_WORLD_47,     "w47",          "" },
   { G_KEY_WORLD_48,     "w48",          "" },
   { G_KEY_WORLD_49,     "w49",          "" },
   { G_KEY_WORLD_50,     "w50",          "" },
   { G_KEY_WORLD_51,     "w51",          "" },
   { G_KEY_WORLD_52,     "w52",          "" },
   { G_KEY_WORLD_53,     "w53",          "" },
   { G_KEY_WORLD_54,     "w54",          "" },
   { G_KEY_WORLD_55,     "w55",          "" },
   { G_KEY_WORLD_56,     "w56",          "" },
   { G_KEY_WORLD_57,     "w57",          "" },
   { G_KEY_WORLD_58,     "w58",          "" },
   { G_KEY_WORLD_59,     "w59",          "" },
   { G_KEY_WORLD_60,     "w60",          "" },
   { G_KEY_WORLD_61,     "w61",          "" },
   { G_KEY_WORLD_62,     "w62",          "" },
   { G_KEY_WORLD_63,     "w63",          "" },
   { G_KEY_WORLD_64,     "w64",          "" },
   { G_KEY_WORLD_65,     "w65",          "" },
   { G_KEY_WORLD_66,     "w66",          "" },
   { G_KEY_WORLD_67,     "w67",          "" },
   { G_KEY_WORLD_68,     "w68",          "" },
   { G_KEY_WORLD_69,     "w69",          "" },
   { G_KEY_WORLD_70,     "w70",          "" },
   { G_KEY_WORLD_71,     "w71",          "" },
   { G_KEY_WORLD_72,     "w72",          "" },
   { G_KEY_WORLD_73,     "w73",          "" },
   { G_KEY_WORLD_74,     "w74",          "" },
   { G_KEY_WORLD_75,     "w75",          "" },
   { G_KEY_WORLD_76,     "w76",          "" },
   { G_KEY_WORLD_77,     "w77",          "" },
   { G_KEY_WORLD_78,     "w78",          "" },
#if 0
   { G_KEY_WORLD_79,     "w79",          "" },
   { G_KEY_WORLD_80,     "w80",          "" },
   { G_KEY_WORLD_81,     "w81",          "" },
   { G_KEY_WORLD_82,     "w82",          "" },
   { G_KEY_WORLD_83,     "w83",          "" },
   { G_KEY_WORLD_84,     "w84",          "" },
   { G_KEY_WORLD_85,     "w85",          "" },
   { G_KEY_WORLD_86,     "w86",          "" },
   { G_KEY_WORLD_87,     "w87",          "" },
   { G_KEY_WORLD_88,     "w88",          "" },
   { G_KEY_WORLD_89,     "w89",          "" },
   { G_KEY_WORLD_90,     "w90",          "" },
   { G_KEY_WORLD_91,     "w91",          "" },
   { G_KEY_WORLD_92,     "w92",          "" },
   { G_KEY_WORLD_93,     "w93",          "" },
   { G_KEY_WORLD_94,     "w94",          "" },
   { G_KEY_WORLD_95,     "w95",          "" },
#endif

   /* Numeric keypad */
   { G_KEY_KP0,          "KP0",          "0" },
   { G_KEY_KP1,          "KP1",          "1" },
   { G_KEY_KP2,          "KP2",          "2" },
   { G_KEY_KP3,          "KP3",          "3" },
   { G_KEY_KP4,          "KP4",          "4" },
   { G_KEY_KP5,          "KP5",          "5" },
   { G_KEY_KP6,          "KP6",          "6" },
   { G_KEY_KP7,          "KP7",          "7" },
   { G_KEY_KP8,          "KP8",          "8" },
   { G_KEY_KP9,          "KP9",          "9" },
   { G_KEY_KP_PERIOD,    "period",       "." },
   { G_KEY_KP_DIVIDE,    "KP_Divide",    "/" },
   { G_KEY_KP_MULTIPLY,  "KP_Multiply",  "*" },
   { G_KEY_KP_MINUS,     "KP_Minus",     "-" },
   { G_KEY_KP_PLUS,      "KP_Plus",      "+" },
   { G_KEY_KP_ENTER,     "KP_Enter",     "\015" },
   { G_KEY_KP_EQUALS,    "KP_Equals",    "=" },

   /* Arrows + Home/End pad */
   { G_KEY_UP,           "Up",           "Up" },
   { G_KEY_DOWN,         "Down",         "Down" },
   { G_KEY_RIGHT,        "Right",        "Right" },
   { G_KEY_LEFT,         "Left",         "Left" },
   { G_KEY_INSERT,       "Insert",       "Insert" },
   { G_KEY_HOME,         "Home",         "Home" },
   { G_KEY_END,          "End",          "End" },
   { G_KEY_PAGEUP,       "Page_Up",      "Page_Up" },
   { G_KEY_PAGEDOWN,     "Page_Down",    "Page_Down" },

   /* Function keys */
   { G_KEY_F1,           "F1",           "F1" },
   { G_KEY_F2,           "F2",           "F2" },
   { G_KEY_F3,           "F3",           "F3" },
   { G_KEY_F4,           "F4",           "F4" },
   { G_KEY_F5,           "F5",           "F5" },
   { G_KEY_F6,           "F6",           "F6" },
   { G_KEY_F7,           "F7",           "F7" },
   { G_KEY_F8,           "F8",           "F8" },
   { G_KEY_F9,           "F9",           "F9" },
   { G_KEY_F10,          "F10",          "F10" },
   { G_KEY_F11,          "F11",          "F11" },
   { G_KEY_F12,          "F12",          "F12" },
   { G_KEY_F13,          "F13",          "F13" },
   { G_KEY_F14,          "F14",          "F14" },
   { G_KEY_F15,          "F15",          "F15" },

   /* Key state modifier keys */
   { G_KEY_NUMLOCK,      "Num_Lock",     "Num_Lock" },
   { G_KEY_CAPSLOCK,     "Caps_Lock",    "Caps_Lock" },
   { G_KEY_SCROLLOCK,    "Scroll_Lock",  "Scroll_Lock" },
   { G_KEY_RSHIFT,       "Shift_R",      "Shift_R" },
   { G_KEY_LSHIFT,       "Shift_L",      "Shift_L" },
   { G_KEY_RCTRL,        "Control_R",    "Control_R" },
   { G_KEY_LCTRL,        "Control_L",    "Control_L" },
   { G_KEY_RALT,         "Alt_R",        "Alt_R" },
   { G_KEY_LALT,         "Alt_L",        "Alt_L" },
   { G_KEY_RMETA,        "Meta_R",       "Meta_R" },
   { G_KEY_LMETA,        "Meta_L",       "Meta_L" },
   { G_KEY_LSUPER,       "Super_L",      "Super_L" },   /* Left "Windows" key */
   { G_KEY_RSUPER,       "Super_R",      "Super_R" },   /* Right "Windows" key */
   { G_KEY_MODE,         "Mode",         "Mode" },   /* "Alt Gr" key */
   { G_KEY_COMPOSE,      "Compose",      "Compose" },   /* Multi-key compose key */

   /* Miscellaneous function keys */
   { G_KEY_HELP,         "Help",         "Help" },
   { G_KEY_PRINT,        "Print",        "Print" },
   { G_KEY_SYSREQ,       "SysReq",       "SysReq" },
   { G_KEY_BREAK,        "Break",        "Break" },
   { G_KEY_MENU,         "Menu",         "Menu" },
   { G_KEY_POWER,        "Power",        "Power" },   /* Power Macintosh power key */
   { G_KEY_EURO,         "Euro",         "\200" },   /* Some european keyboards */
   { G_KEY_UNDO,         "Undo",         "Undo" }    /* Atari keyboard has Undo */
};


